### ISSUE TITLE
如果能支持Webpack就好了……

### ISSUE THREAD

**Issue by mopperwhite** [hustcc/canvas-nest.js#13]
或者至少支持只对特定元素用……

在Webpack里import然后就直接对整个页面生效了= =

**Comment by mopperwhite** [comment]
主要是……用Vue Router做单页应用的时候只想让部分组件带背景……

**Comment by hustcc** [comment]
不错的思路，不过这个代码可能需要再重构一下。

**Comment by TechQuery** [comment]
@mopperwhite 你要的支持特定元素 —— https://techquery.github.io/StarMap/

**Comment by hustcc** [comment]
@TechQuery 把 jq 干掉~

**Comment by TechQuery** [comment]
@hustcc 
jQuery、[iQuery](https://github.com/TechQuery/iQuery.js) 封装的一些实用方法，实在不是 ES 5、W3C API 能轻松替代的~

**Comment by zfowed** [comment]
我基于你的插件造了个支持模块引入的轮子...
如果不喜欢的话告知我会删掉的
[canvas-nest-class.js](http://www.zfowed.com/2018/04/30/canvas-nest-class.js%20%E4%B8%80%E6%AC%BE%E5%A5%BD%E7%9C%8B%E7%9A%84%E7%B2%92%E5%AD%90%E8%83%8C%E6%99%AF%E6%8F%92%E4%BB%B6)

**Comment by hustcc** [comment]
can do it on v2.0.0. @zfowed @mopperwhite
