### ISSUE TITLE
背景动画如何实现根据不同设备实现开启和关闭？

### ISSUE THREAD

**Issue by zipeijun** [hustcc/canvas-nest.js#17]
这个背景动画很好玩，但是只能设置开启或关闭，这就导致一个问题，在桌面端的体验很好，但是在移动端就显得十分的渣乱。

想知道可不可以实现根据访问者使用设备情况，只在桌面端开启，移动端自动关闭？

如果可以，如何实现？

动画具体效果可以在桌面端和移动端分别打开我的[博客](https://zipeijun.github.io)体验

**Comment by hustcc** [comment]
可以实现，可以在 js 中判断当前用户的情况（user agent），然后 如果需要显示，就把这个脚本加到 html 中即可，否则不加。

**Comment by zipeijun** [comment]
@hustcc 不好意思，追问一下。我使用的是 Hexo 的 NexT 中自带的，不知道把哪个脚本追加到哪里？如果方便的话，可以详细指导下么？
