### ISSUE TITLE
一点想法？

### ISSUE THREAD

**Issue by skphetz** [hustcc/canvas-nest.js#19]
我已经在我的博客上加了这个，觉得能不能弄一个随机颜色？（我不是很懂这些东西因此如果这是个不切实际的想法请别喷我QAQ）

**Comment by hustcc** [comment]
可以啊，但是随机颜色是每次刷新随机颜色还是一直在变颜色？

**Comment by skphetz** [comment]
我的想法就是一直没有被牵引的是不用管，被鼠标牵引着的实时刷新随机的颜色

**Comment by yangruoyang** [comment]
你谁啊 骚年

Sent from my Sony Xperia™ smartphone

---- skphetz wrote ----


我的想法就是一直没有被牵引的是不用管，被鼠标牵引着的实时刷新随机的颜色

**Comment by skphetz** [comment]
？？？

**Comment by hustcc** [comment]
随机颜色太闪烁，可定不好看的！哈哈
