### ISSUE TITLE
A switch to turn off the special effects on mobile 

### ISSUE THREAD

**Issue by gengxuelei** [hustcc/canvas-nest.js#24]
```
# Canvas-nest
canvas_nest: true

# three_waves
three_waves: false

# canvas_lines
canvas_lines: false

# canvas_sphere
canvas_sphere: false
```
Can you set a switch to close the canvas effect on a mobile device.
Just like this:
https://github.com/EYHN/hexo-helper-live2d/blob/master/index.js#L67

Another issue：
https://github.com/hexojs/hexo/issues/2931

**Comment by hustcc** [comment]
can do it on v2.0.0.

**Comment by sli1989** [comment]
@hustcc how to control it in v2.0.1?

**Comment by hustcc** [comment]
You can detect the env to decide whether load canvas nest or not.

**Comment by sli1989** [comment]
Thanks, can it do in swig? I want to add condition in Next theme, but don't know how to do it. Is there any examples I can look around,

**Comment by viclw17** [comment]
You can add a function in the script to return the type of the platform, and use it to branch in the drawing function. Working fine in my case.
``` 
  function getBrowserType() {
  	var browserType = "Undefined";
  	var browserAgent = navigator.userAgent;
  	if (browserAgent != null) {
  		if	(	browserAgent.indexOf("Mobile") >= 0
  			||	browserAgent.indexOf("Android") >= 0
  			||	browserAgent.indexOf("BlackBerry") >= 0
  			||	browserAgent.indexOf("iPhone") >= 0
  			||	browserAgent.indexOf("iPad") >= 0
  			||	browserAgent.indexOf("iPod") >= 0
  			||	browserAgent.indexOf("Opera Mini") >= 0
  			||	browserAgent.indexOf("IEMobile") >= 0
  			) {
  			browserType = "MOBILE";
  		}
  		else {
  			browserType = "DESKTOP";
  		}
  	}
  	return browserType;
  }
```

In function draw_canvas() ,
```
function draw_canvas() {
     if(getBrowserType() === "DESKTOP"){
         // ...
     }
}
```
[Ref.](http://community.openfl.org/t/html5-canvas-a-way-to-disable-effect-on-mobile/10283)
