### ISSUE TITLE
插件CSS层级有点问题，麻烦楼主帮忙看看呀~

### ISSUE THREAD

**Issue by YICHION** [hustcc/canvas-nest.js#31]
楼主好~
发现插件canvas-nest.js在朋友的网页上效果非常赞，就下载到了自己的wordpress上。
但貌似安装插件并正确设置之后，打开网页并没有任何效果。
检查了一下并询问了主题的作者，说是CSS层级有点问题，还麻烦帮忙查一下咯，谢谢了~

P.S 附上网站链接
yiqin.me

**Comment by ChrisXJH** [comment]
原因是被顶层的东西挡住了。你可以把白色的区域设opacity：0。我的网站就是这么干的 chrisxu.me

**Comment by hustcc** [comment]
正解，因为你设置了背景颜色导致挡住。
