### ISSUE TITLE
如何在hugo里面使用？

### ISSUE THREAD

**Issue by Bushite** [hustcc/canvas-nest.js#48]
我把canvas-nest.js这一个文件放在hugo的static/js文件夹内，然后在配置文件中添加这个js，最后只显示了非常少量的线条。线条聚集的点也和鼠标位置有偏差。

**Comment by Bushite** [comment]
我把canvas-nest.js这一个文件放在hugo的static/js文件夹内，然后在配置文件中添加这个js，最后只显示了非常少量的线条。线条聚集的点也和鼠标位置有偏差。

**Comment by hustcc** [comment]
有示例吗？

**Comment by Bushite** [comment]
@hustcc wenboran.com

**Comment by hustcc** [comment]
因为高度太高，导致线条比较少！

偏差应该是因为有一个 header，这个是一个 bug 需要修复~

**Comment by ZYSzys** [comment]
@Bushite 应该是你的 body 布局问题。

Refs: https://github.com/Bushite/Bushite.github.io/pull/1
