### ISSUE TITLE
考虑监测一下是否接通电源？

### ISSUE THREAD

**Issue by imba-tjd** [hustcc/canvas-nest.js#60]
RT。笔记本，正常情况下占点CPU就算了。但如果没有接通电源还大量占用就很伤了。
或者加个选项，允许控制是否在未接通电源时禁用效果？

**Comment by hustcc** [comment]
怎么获取是否接入电源？

**Comment by imba-tjd** [comment]
我错了😂。我是之前看到FF的WebRender能检测只接通电源时使用，现在想起来它用的不是JS的API
